### ISSUE TITLE
Wiki/Tutorial?

### ISSUE THREAD

**Issue by ciptard** [Icybee/Icybee#1]
Hi,
is there a tutorial to install this CMS? I'm a web designer and I wanna try it. I really like the demonstration on www.icybee.org, the use of bootstrap is really cool too.

Thank you.

**Comment by olvlvl** [comment]
Hi,

Thanks for your interest in Icybee !

Currently there is no tutorial on how to install Icybee, and the repository cannot be used to retrieve the project with all its dependencies yet, but I'm working on a demo that will hopefully be finished in the following weeks. I could send you a message when it's ready if you want.

Best regards,

Olivier.

**Comment by ciptard** [comment]
Yeah,
Glad to hear that. I hope you can give me a note when it's ready. You can contact me to my email address (open my github public profile, message button on the top-right).

Thank you,
ciptard.

**Comment by olvlvl** [comment]
Hello,

You can now [download the Icybee's epic demonstration](http://icybee.org/icybee-demo-latest.zip), and follow the [installation guide](https://github.com/Icybee/Icybee/wiki/Installation-guide-for-Icybee%27s-epic-demonstration) to install the demo on your computer or server.

Enjoy!

**Comment by ciptard** [comment]
Great!
I'll try it this week.

Thanks.
ciptard

**Comment by ciptard** [comment]
btw,
is it ready for production environment?

**Comment by olvlvl** [comment]
The previous version of the software, which was called "Publishr", has been used in production for more than two years now. Here are some references:

http://www.wdpublisher.com/references/

We are currently working on three new websites which will be using Icybee.

**Comment by serialbob** [comment]
Hi i used WPPublisher on a project. WDPublisher to Icybee migration will be possible ?

Thanks

**Comment by olvlvl** [comment]
I created a script to migrate (Wd)Publishr database tables to Icybee. It was enough to migrate all my projects, although some minor additional work was needed because naming scheme has changed. Note that Publishr modules won't be compatible with Icybee, the code has vastly changed (namespace and all) although the spirit stayed the same.

I shall release the script later this month as a repository. If you need help upgrading to Icybee, don't hesitate to contact me.

**Comment by serialbob** [comment]
Ok, tkanks

**Comment by interlan** [comment]
Not able to install IcyBee!!!
Win XP , wamp server on c:\wamp, so localhost is c:\wamp\www. Copied everything in directory c:\wamp\www\icybeedemo. Error -> it tries to find folder REPOSITORY under root not under my subfolder. I play with .htaccess and RewriteBase -> NO SUCCESS.
I create a virtual host icybeedemo.pet pointing at c:\wamp\www\icybeedemo. Now, every URL gives blank screen.
Any help?

**Comment by olvlvl** [comment]
@interlan Icybee has not been designed to work in a subfolder, and has never been tested under such setup. I advise you to create a virtual host and install Icybee there. For instance, you could create a "icybee.localhost" virtual host to try out Icybee.

**Comment by interlan** [comment]
Thanks for taking time to answer...

As I said I have already created a virtual host icybeedemo.pet (the pet is from my name Peter!) but I get a blank screen. I used a portable wamp and I attach a screenshot.
![vhost](https://f.cloud.github.com/assets/3278013/448898/2206d128-b260-11e2-8ab2-dbbed2c32f64.jpg)

**Comment by olvlvl** [comment]
@interlan Could you check that `display_errors` is "On" in php.ini ? Also, could you create a `info.php` file with the following content :

``` php
<?php

phpinfo();
```

An make a screenshot of the result that should be at http://www.icybeedemo.pet/info.php ?

Thanks

**Comment by interlan** [comment]
@olvlvl  screenshot follows.
![phpinfo](https://f.cloud.github.com/assets/3278013/450306/791cf41a-b28d-11e2-8b0f-b2c584743713.png)

**Comment by olvlvl** [comment]
From what I see :
- short_open_tag is set to Off, but if I remember correctly "<?=" is always supported in PHP5.4.
- I don't know the numeric value of error_reporting, but it should be set to E_ALL.
- SQLite driver for PDO is missing. It is required by some caches.

Please try enabling the SQLite driver and tell me if it works. Is there any error message displayed ?

If you can enable the driver you might want to try the new installer. I finished it this afternoon. Please read the "install" section in the README of the following repo:

https://github.com/Icybee/Starter
