### ISSUE TITLE
Is it Open Source?

### ISSUE THREAD

**Issue by interlan** [Icybee/Icybee#2]
Is icybee OpenSource?
If yes when will there be a composer installation with all the dependencies?
If you send me to the demo, is it done with the latest version?

Thanks

**Comment by olvlvl** [comment]
Hi Interlan,

Yes, Icybee is open source. You actually need a starter kit to install the CMS. A basic stater kit is available here:

https://github.com/Icybee/Starter

The install process is described in the "Installation" section.

Please be indulgent with the template included, it is VERY basic. I'm working on a "useful" one but lately I spent a lot of time on the overhaul of the UI elements managing the records.

There is a demo of the CMS and some of its features here:

http://demo.icybee.org/

The demo is quite old. Please check this website, which runs of the latest version:

http://www.transitionspro.fr/

Please, try to install the Starter kit. I pushed a lot of changes recently. Let me know if everything works.
